// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"babycare/internal/biz/car"
	"babycare/internal/conf"
	"babycare/internal/data"
	"babycare/internal/server"
	"babycare/internal/service/api"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	engineDb := data.NewEngineDbRw(confData, logger)
	dataProviderCollection := &data.DataProviderCollection{
		EngineDb: engineDb,
	}
	dataData, cleanup, err := data.NewData(confData, dataProviderCollection, logger)
	if err != nil {
		return nil, nil, err
	}
	iCarRepo := data.NewCarData(dataData, logger)
	carBiz := car.NewCarBiz(iCarRepo, logger)
	service := api.NewService(carBiz, logger)
	grpcServer := server.NewGRPCServer(confServer, service, logger)
	httpServer := server.NewHTTPServer(confServer, service, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
