// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: tree/v1/tree.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Tree_GetTree_FullMethodName = "/api.tree.v1.Tree/GetTree"
)

// TreeClient is the client API for Tree service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TreeClient interface {
	GetTree(ctx context.Context, in *GetTreeRequest, opts ...grpc.CallOption) (*GetTreeReply, error)
}

type treeClient struct {
	cc grpc.ClientConnInterface
}

func NewTreeClient(cc grpc.ClientConnInterface) TreeClient {
	return &treeClient{cc}
}

func (c *treeClient) GetTree(ctx context.Context, in *GetTreeRequest, opts ...grpc.CallOption) (*GetTreeReply, error) {
	out := new(GetTreeReply)
	err := c.cc.Invoke(ctx, Tree_GetTree_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TreeServer is the server API for Tree service.
// All implementations must embed UnimplementedTreeServer
// for forward compatibility
type TreeServer interface {
	GetTree(context.Context, *GetTreeRequest) (*GetTreeReply, error)
	mustEmbedUnimplementedTreeServer()
}

// UnimplementedTreeServer must be embedded to have forward compatible implementations.
type UnimplementedTreeServer struct {
}

func (UnimplementedTreeServer) GetTree(context.Context, *GetTreeRequest) (*GetTreeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTree not implemented")
}
func (UnimplementedTreeServer) mustEmbedUnimplementedTreeServer() {}

// UnsafeTreeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TreeServer will
// result in compilation errors.
type UnsafeTreeServer interface {
	mustEmbedUnimplementedTreeServer()
}

func RegisterTreeServer(s grpc.ServiceRegistrar, srv TreeServer) {
	s.RegisterService(&Tree_ServiceDesc, srv)
}

func _Tree_GetTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServer).GetTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tree_GetTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServer).GetTree(ctx, req.(*GetTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tree_ServiceDesc is the grpc.ServiceDesc for Tree service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tree_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.tree.v1.Tree",
	HandlerType: (*TreeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTree",
			Handler:    _Tree_GetTree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tree/v1/tree.proto",
}
